### PR TITLE
Add pre-commit and dev packages

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Review by saisankargochhayat — APPROVED** [review]
Awesome! Btw is pre-commit enabled on this repo?

**Comment by pacospace** [comment]
> Awesome! Btw is pre-commit enabled on this repo?

@harshad16 ?

**Comment by harshad16** [comment]
yes @pacospace  , pre-commit is enabled https://github.com/thoth-station/workflow-helpers/blob/da6b3f4d279308aeb6744e7371a9add0cc4cb6fe/.aicoe-ci.yaml#L2

**Comment by pacospace** [comment]
> yes @pacospace , pre-commit is enabled
> 
> https://github.com/thoth-station/workflow-helpers/blob/da6b3f4d279308aeb6744e7371a9add0cc4cb6fe/.aicoe-ci.yaml#L2

Thanks @harshad16!

**Pull request merged**
