### PR TITLE
github create deployment script

### PR DESCRIPTION
**Pull request by goern**
I put a few github related scripts in this, so we can use them in tekton or argo workflows

- update all the CI/CD configs
- relocked dependencies
- add two scripts to manage github deployment status

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
lgtm :+1: 
@KPostOffice  PTAL
@goern  Please remove WIP when this PR is ready.

**Review by KPostOffice — COMMENTED** [review]
/lgtm

**Comment by goern** [comment]
@KPostOffice could you have a look if that mypy issue is easy to fix? thx!

/assign @KPostOffice

**Comment by KPostOffice** [comment]
@goern 
Easy fix. In `workflow_helpers/common.py` remove the import of `Metrics` and import `from typing import Union`. Then, replace the type hint `Metric` with `Union[Counter, Gauge]`

**Comment by KPostOffice** [comment]
Do you want to include this here? Otherwise I can open a new PR with this change and you can rebase.

**Pull request merged**
