### PR TITLE
get inspection info from env

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/thoth-application/issues/398

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Grab contents from env and put them into a file. I am not sure if this was what was intended by the issue, if there is some way to get these values from inspection output it would be better to parse that.

### CODE REVIEW

**Comment by pacospace** [comment]
> ## Related Issues and Dependencies
> Related: [thoth-station/thoth-application#398](https://github.com/thoth-station/thoth-application/issues/398)
> 
> ## This introduces a breaking change
> * [ ]  Yes
> * [x]  No
> 
> ## This Pull Request implements
> Grab contents from env and put them into a file. I am not sure if this was what was intended by the issue, if there is some way to get these values from inspection output it would be better to parse that.

Yes @KPostOffice the idea was to get env, but you could also retrieve the inspection result file from local (not sure what is the advantage if the env variables already have all information for the message). Also as we do not expect more messages, instead of storing a single message into a file we could use `send-message` task for single message in a workflow. WDYT?

**Comment by pacospace** [comment]
@KPostOffice please rebase

**Comment by KPostOffice** [comment]
@pacospace

**Review by pacospace — APPROVED** [review]
:rocket: Thanks!!

**Pull request merged**
