### PR TITLE
store default empty string for other source types

### PR DESCRIPTION
**Pull request by harshad16**
## Related Issues and Dependencies

Related-To: #67 

## This introduces a breaking change

- [x] No

## This Pull Request implements

- save empty string to the metadata_origin.

## Description

store default empty string for other source types
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
LGTM! :)

**Comment by harshad16** [comment]
works :
```
STEP                        TEMPLATE                                     PODNAME                      DURATION  MESSAGE
 ✖ adviser-966dfb06         adviser                                                                                                                     
 ├-✔ advise                 advise/advise                                adviser-966dfb06-1978627955  1m                                                
 ├-✖ investigator-producer  investigator-producer/investigator-producer  adviser-966dfb06-2442242903  38s       failed with exit code 1                 
 ├-✔ graph-sync-advise(0)   graph-sync/graph-sync                        adviser-966dfb06-2323849101  34s                                               
 ├-✔ trigger-integration    trigger-integration/trigger-integration      adviser-966dfb06-3283912318  30s   
```

**Review by pacospace — APPROVED** [review]
Thanks!! :100:

**Pull request merged**
