### PR TITLE
make sure secret is file before opening

### PR DESCRIPTION
**Pull request by KPostOffice**
when testing, the default directory had a reference to a directory called "data" one level up

Signed-off-by: Kevin <kpostlet@redhat.com>

## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [ ] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Comment by KPostOffice** [comment]
@harshad16 PTAL

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks :+1:

**Pull request merged**
