### PR TITLE
use python 3.8 fixes pydantic issues

### PR DESCRIPTION
**Pull request by KPostOffice**
## Description

Update to py3.8

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
💯

**Comment by pacospace** [comment]
please take care of reabase :)

**Review by harshad16 — CHANGES_REQUESTED** [review]
please also address these: 

change this https://github.com/thoth-station/workflow-helpers/blob/856927fe1b61a01213ed74d32dea315f5d444ac1/.aicoe-ci.yaml#L4
to py38. 

https://github.com/thoth-station/workflow-helpers/blob/856927fe1b61a01213ed74d32dea315f5d444ac1/.thoth.yaml#L10

**Review by harshad16 — APPROVED** [review]
thanks :100:

**Pull request merged**
