### PR TITLE
fix list out of range

### PR DESCRIPTION
**Pull request by bissenbay**
Fixes: https://github.com/thoth-station/workflow-helpers/issues/92

### CODE REVIEW

**Comment by pacospace** [comment]
I'm not sure here, we submit to solver using `package_name===package_version`, some components is submitting in the wrong way? I opened https://github.com/thoth-station/workflow-helpers/pull/95 to check what happens. Do you have inputs for the same workflow that failed?

**Comment by bissenbay** [comment]
@fridex @pacospace Do we need to consider all cases such as '<' | '<=' | '!=' | '==' | '>=' | '>' | '~=' | '==='? or just two cases === and ==?

**Comment by fridex** [comment]
> @fridex @pacospace Do we need to consider all cases such as `'<' | '<=' | '!=' | '==' | '>=' | '>' | '~=' | '==='`? or just two cases `===` and `==` ?

Related: https://github.com/thoth-station/thoth-application/issues/443

**Comment by bissenbay** [comment]
I think this can be closed as we will be moving forward with changing the logic of one the workflows and keep track in https://github.com/thoth-station/workflow-helpers/issues/106.

**Pull request closed without merging**
